Finish assignment 4
webprogramminghack/assignment-class4 pull request #2
Opened 2024-08-04 16:59 UTC by novelyr

mohon arahan pak
saya merasa masih belum optimal di flex, saat membesar mengecil mau pindah, tapi saya tidak melihat dia bisa stretch

2024-08-05 14:22 UTC, novelyr commented
untuk flex sudah saya perbaiki pak, namun ada kendala di bentuk logo, seperti agak menaik dibanding "nav" padahal tidak ditambah padding atau sejenisnya

2024-08-06 06:08 UTC, webprogramminghack commented
logonya memang begitu dari svg nya

2024-08-06 16:53 UTC, webprogramminghack requested changes
Tolong baca comment dan betulkan.

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  flex-grow: 5;
flex-grow tidak perlu ditempatkan di sini

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  flex-grow: 5;
dihapus saja

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  height: 4rem;
Cek lagi di design, ini harusnya 72px (4.5rem), bukan 64px.

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  flex-wrap: wrap;
Jangan memberikan flex-wrap sembarangan. Coba cek di design, pada versi mobile item (children) dari logo-nav-wrapper tidak pindah ke line berikutnya. Flex-wrap hanya diberikan jika kita ingin item dari suatu container pindah ke line berikutnya jika tempatnya tidak cukup.

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  font-weight: 600;
line-heightnya mana? Jangan pernah lupa line-height, walaupun terkesan simpel, tapi ini akan mempengaruhi tinggi.

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  height: 21.25rem;
Jangan pakai height, disini harusnya kita pakai padding. Penggunaan height harus sangat berhati-hati, bayangkan jika layarnya kita kecilkan sampai sebesar tablet, lalu tulisannya pindah ke line berikutnya, tentunya height tidak akan bertambah. Tapi kalau kita menggunakan padding, tentunya besar dari pricing-header akan bertambah.
![CleanShot 2024-08-06 at 23 07 28@2x](https://github.com/user-attachments/assets/fdc2e4b0-7244-42c3-aa8d-cc2c59905e3d)
```
padding-top: 6rem;
padding-bottom: 10rem;
```

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +.header-actions .btn-primary {
Cukup target `.header-actions` nya saja, buttonnya tidak usah. Buttonnya kan ada di dalam `.header-actions`, kalau kita berikan `display: none;` kepada containernya, segala isinya juga akan hilang.

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  padding: 0.75rem 1rem;
Jangan berikan padding vertical terhadap button. Bayangkan kalau isi textnya lebih pendek, tidak semua huruf sama tinggi, bayangkan juga jika tidak ada huruf besar di dalamnya, maka tinggi button akan ketergantungan dengan konten yang ada di dalamnya. Cara yang benar untuk button adalah berikan padding horizontal saja. Untuk tinggi diatur oleh height.

Pada design heightnya 44px.
```
height: 2.75rem;
padding: 0 1rem;
```

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  border-radius: 8px;
Jangan menggunakan px, ganti ke rem. Kita pingin sesuatu yang relatif terhadap font size di browser setting user. Bayangkan jika elemennya membesar tapi border-radiusnya tetap sama, maka sisinya akan menjadi runcing. So, ganti ke rem.

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  text-align: center;
text-align cukup ditaruh 1 kali di orang tuanya saja, ini adalah property yang inherit. Terapkan di `.pricing-header`. Dengan menerapkan `text-align: center;` di `.pricing-header`, otomatis semua anaknya ketengah secara horizontal. Jadi jangan diberikan satu persatu ke anaknya, cukup 1x ke orang tuanya, maka semua anaknya mendapatkan efek yang sama.

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  justify-content: center;
Hilangkan `justify-content: center`. Kenapa perlu center kalau di design dia menghabiskan space dari ujung kiri ke ujung kanan?

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  flex-direction: column;
Tidak perlu memberikan `display: flex'` & `flex-direction: column;` kepada sesuatu yang tidak perlu.
Yang butuh jarak hanya button saja, sisanya kan tidak perlu.

Secara default element dengan `display: block` itu kan sudah mengurut dari atas ke bawah, so tidak perlu `display: flex;`. Yang perlu diberikan `display: flex;` dan `justify-content: center;` justru adalah `card-features`, bukan `.card`. Karena anak dari `.card-features` memiliki gap yang sama, sehingga lebih efisien jika dijadikan flex.
![CleanShot 2024-08-06 at 23 24 14@2x](https://github.com/user-attachments/assets/9d41d6d9-5b78-4ceb-8ab1-ced741040feb)

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  display: flex;
Jangan menggunakan `display: flex;` dan `flex-direction: column` untuk sesuatu yang tidak perlu. Coba lihat itemnya (anaknya), bukankah anaknya semua memiliki `display: block` secara default? Itu kan sudah menumpuk dari atas ke bawah (utara ke selatan), untuk apa memberikan flex dan flex-direction.

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  border-radius: 10px;
Ganti semua px ke rem.

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  width: 6px;
Ganti semua px ke rem.

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  padding: 1.5rem;
Coba cek lagi padding `.card`, di design semua sisi adalah 32px (2rem).
![CleanShot 2024-08-06 at 23 33 36@2x](https://github.com/user-attachments/assets/71502c16-e935-46b7-b57e-7e87c794cd95)

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  padding: 1rem 7rem 1rem 7rem;
Seperti yang saya sebutkan, jangan pernah memberikan vertical padding ke button, berikan height saja. Hanya horizontal padding saja yang boleh diberikan (cek comment sebelumnya terkait ini).

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  justify-content: center;
Coba cek design, apakah listnya berada di tengah? Ini harusnya di kiri. So, buang `justify-content: center;` dari `.card-features`.

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +  justify-content: center;
Kenapa perlu `justify-content: center;` dan `align-items: baseline`. Tolong di remove. Sebelum menggunakan css property, bandingkan dulu dengan design.

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +.badge {
Hasil badgenya terlihat lebih tinggi, sedangkan yang di design terlihat lebih pendek (lihat gambar).
![CleanShot 2024-08-06 at 23 47 30@2x](https://github.com/user-attachments/assets/d51326d1-008c-426d-89f2-8501010da53c)

Saya akan kasih contoh, harusnya begini:
```
.card-header .badge-container .badge {
  display: flex;
  align-items: center;
  gap: 0.375rem;
  border-radius: 0.375rem;
  border: 1px solid #d0d5dd; /*disini gpp menggunakan px, selama itu 1px. biasanya pada border dibiarkan 1px, kalau mau diganti ke rem juga bisa. Namun yang lainnya tolong jadikan rem.*/
  padding: 0 0.5rem;
  height: 1.5rem;
}
```

Ingat, harus 100% sama dengan design. Design itu harganya mahal, company mengeluarkan cost besar untuk tim designer.

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +    margin-top: -5rem;
Ini harusnya yang diberikan `margin-top` adalah `.pricing-cards`, bukan `.container` yang ada di dalam `.pricing-cards`. Valuenya juga salah. Harusnya `margin-top: -6rem;`

2024-08-06 16:53 UTC, webprogramminghack commented on css/style.css
> +    padding: 0 2rem;
Coba cek di file `general.css`, padding sudah ada disana, tidak usah diberikan lagi.

2024-08-07 11:22 UTC, novelyr commented on css/style.css
> +  height: 21.25rem;
untuk ini, padding-top 4 rem dan padding bottom 8 rem kan pak di desain mobile?

2024-08-07 11:22 UTC, novelyr commented on css/style.css
> +  flex-grow: 5;
sudah pak

2024-08-07 11:22 UTC, novelyr commented on css/style.css
> +  height: 4rem;
oke pak, ternyata 72 saya cek lagi di desain yg mobile, terima kasih

2024-08-07 11:25 UTC, novelyr commented on css/style.css
> +  flex-wrap: wrap;
karena desain tidak tertampang kalau dia ngeflex wrap, berarti artinya tidak perlu flex wrap ya pak. yang jelas terlihat saja ya

2024-08-07 11:26 UTC, novelyr commented on css/style.css
> +  font-weight: 600;
baik pak, setiap ada tulisan tulisan selalu diikutkan line height nya ya meskipun hanya 1 baris

2024-08-07 11:27 UTC, novelyr commented on css/style.css
> +.header-actions .btn-primary {
ini saya target btn nya, karena di dalam html header-action saya berikan btn hamburger juga pak, nanti hilang kalau saya target hanya header actionnya. Bagaimana pak?

2024-08-07 11:30 UTC, novelyr commented on css/style.css
> +  padding: 0.75rem 1rem;
baik pak, akan saya ingat-ingat kalau button hanya perlu padding horizontal. Untuk vertikal biar menyesuaikan isi konten ya pak, kita hanya mengatur height button ya.

2024-08-07 11:31 UTC, novelyr commented on css/style.css
> +  border-radius: 8px;
siap pak, untuk semua yang rem saya ganti ke px, termasuk yg 1px juga ya

2024-08-07 11:33 UTC, novelyr commented on css/style.css
> +  text-align: center;
baik pak

2024-08-07 11:36 UTC, novelyr commented on css/style.css
> +  text-align: center;
agar tidak redundant dan lebih rapi ya. tampaknya akan lebih terlihat kalau misal pakai scss ya pak, jadi lebih bisa melihat mana yg bisa dikasih ortunya, mana yg perlu ke anaknya. Setelah melihat scss kemarin, lebih mudah dilihat untuk pengaturan letak desainnya pak. CSS vanila ini ternyata harus lebih jeli melihat mana orangtuanya siapa, hehe

2024-08-07 11:37 UTC, novelyr commented on css/style.css
> +  justify-content: center;
baik pak saya hilangkan ya. Tanpa justify center dia otomatis sudah rapi kiri kanannya ya pak? tidak miring2?

2024-08-07 11:42 UTC, novelyr commented on css/style.css
> +  flex-direction: column;
oke pak, setelah saya buang, <a> bagian get started itu jadi rusak pak, karena dia inline kan ya. Jadi daripada flex di orangtua, si get started yang saya jadikan display block saja ya

2024-08-07 11:44 UTC, novelyr commented on css/style.css
> +  display: flex;
oke pak, tidak perlu kode yang tidak berguna ya. Untuk flex di card-header saya buang saja ya. Yang dipertahankan flex di bagian badge kan pak ya, yg ada bulet bulet hiasan itu ya

2024-08-07 11:48 UTC, novelyr commented on css/style.css
> +  display: flex;
![image](https://github.com/user-attachments/assets/f4c719b3-6da8-4d1b-a55b-3639b68930b4)
saya baru ingat pak, itu saya kasih flex, karena ketika saya hilangkan, si bordernya jadi melebar menghabiskan width pak.

2024-08-07 12:03 UTC, novelyr commented on css/style.css
> +  display: flex;
sementara saya hilangkan dulu pak ya, belum nemu solusi lagi ini

2024-08-07 12:03 UTC, novelyr commented on css/style.css
> +  border-radius: 10px;
siap pak

2024-08-07 12:03 UTC, novelyr commented on css/style.css
> +  width: 6px;
oke pak

2024-08-07 12:05 UTC, novelyr commented on css/style.css
> +  padding: 1.5rem;
maaf pak, untuk ini saya lihat di desain mobile dia padding hanya 1.5rem, yg desktop baru 2 rem, sudah saya masukkan di media

2024-08-07 12:17 UTC, novelyr commented on css/style.css
> +  padding: 1rem 7rem 1rem 7rem;
siap pak sudah saya perbaiki, namun saya hanya menemukan solusi pakai display flex agar bisa memakai align-items dan justify -content, biar tulisannya ditengah. Apa benar demikian pak?

2024-08-07 12:18 UTC, novelyr commented on css/style.css
> +  justify-content: center;
oiya pak bila diperhatikan ternyata dia ke kiri ya startnya

2024-08-07 12:19 UTC, novelyr commented on css/style.css
> +  justify-content: center;
niatnya agar mepet kiri pak, jadi tidak perlu ya ini

2024-08-07 12:25 UTC, novelyr commented on css/style.css
> +.badge {
siap pak, sudah saya samakan pak, ada selisih di padding ternyata

oiya, saya masih ada masalah di bordernya badge-container, lebar sekali ini pak

2024-08-07 12:30 UTC, novelyr commented on css/style.css
> +    margin-top: -5rem;
yg diberikan ke arah org yg lebih tua lagi pak ya, yg lebih luar begitu ya

untuk desain mobile saya hitung ulang malah dapat 64 px (128 - 64), mohon koreksi bila salah pak
yg 6 rem itu saya dapat di hitungan desktop, sudah saya masukkan media pak

2024-08-07 12:31 UTC, novelyr commented on css/style.css
> +    margin-top: -5rem;
oiya pak ternyata yg di media, saya naruhnya -5rem, harusnya -6rem ya

2024-08-07 12:33 UTC, novelyr commented on css/style.css
> +    padding: 0 2rem;
padding yg ini saya pasang di media karena di desain mobile padding hanya 1rem pak yg horizontal. Jadi ketika responsive ke desktop, biar kembali ke 2 rem saya berikan perintah padding ini pak. Betul demikian kah?

2024-08-07 16:02 UTC, edwin-anderson requested changes

2024-08-07 16:02 UTC, edwin-anderson commented on css/style.css
> +.header-actions .btn-primary {
Masih belum betul. Harusnya cukup target `.header-actions` saat ingin menghilagnkan `.btn-secondary` dan `.btn-primary`

2024-08-08 10:12 UTC, webprogramminghack commented on css/style.css
> +  justify-content: center;
Tidak mungkin miring karena childrennya kita berikan flex-grow, pasti tempatnya habis terpakai.

2024-08-08 10:14 UTC, webprogramminghack commented on css/style.css
> +.header-actions .btn-primary {
![CleanShot 2024-08-08 at 17 14 06@2x](https://github.com/user-attachments/assets/83a2535e-65df-4d2d-acf0-436764f903d1)
Harusnya `.hamburger-icon` adalah bagian terpisah.

2024-08-08 10:16 UTC, webprogramminghack commented on css/style.css
> +    padding: 0 2rem;
Edit di bagian general, gunakan media query. Pada bagian mobile harusnya padding kiri dan kanan sebanyak 1rem, sedangkan desktop 2rem.

2024-08-08 10:18 UTC, webprogramminghack commented on css/style.css
> +  flex-direction: column;
Betul, jadikan display block, jadi otomatis tempatnya dihabiskan karena karakteristik elemen display block adalah menghabiskan tempat secara horizontal.

2024-08-08 15:31 UTC, novelyr commented on css/style.css
> +    padding: 0 2rem;
oke pak, baru sadar bisa ada cara demikian, saya cobanya

2024-08-08 15:32 UTC, novelyr commented on css/style.css
> +.header-actions .btn-primary {
oke sudah pak

2024-08-19 10:28 UTC, closed without merging